-- 02_seed.sql
USE PatientDoctorPortal;
GO

-- Password hash for '123456' generated by bcrypt with 10 rounds.
-- We'll insert plain now and update via app if needed, but better to store hash:
-- For demo, we provide a precomputed hash to avoid bcrypt in SQL.
-- Precomputed hash for '123456':
-- $2b$10$8PrKax1dQsz4IYYx1nN8wO8sYkYt7m0GAnbS5r0RZzJkpXJb3Vn2y
DECLARE @DoctorHash NVARCHAR(255) = '$2b$10$8PrKax1dQsz4IYYx1nN8wO8sYkYt7m0GAnbS5r0RZzJkpXJb3Vn2y';
DECLARE @PatientHash NVARCHAR(255) = '$2b$10$8PrKax1dQsz4IYYx1nN8wO8sYkYt7m0GAnbS5r0RZzJkpXJb3Vn2y';

INSERT INTO Users (Email, PasswordHash, FullName, Phone, Gender, DOB, Role)
VALUES
('doctor1@demo.com',  @DoctorHash, 'Dr. Nguyen Van A', '0900000001', 'M', '1980-01-01', 'doctor'),
('patient1@demo.com', @PatientHash, 'Le Thi B',        '0900000002', 'F', '1998-05-20', 'patient');

DECLARE @DoctorUserId INT = (SELECT UserId FROM Users WHERE Email='doctor1@demo.com');
DECLARE @PatientUserId INT = (SELECT UserId FROM Users WHERE Email='patient1@demo.com');

INSERT INTO Doctors (UserId, Specialty, Bio, Room, Level)
VALUES (@DoctorUserId, N'Tim mạch', N'Bác sĩ chuyên khoa tim mạch', N'P201', N'CKI');

INSERT INTO Patients (UserId, Address, InsuranceNo)
VALUES (@PatientUserId, N'123 Lê Lợi, Q.1', N'INS-001');

DECLARE @DoctorId INT = (SELECT DoctorId FROM Doctors WHERE UserId=@DoctorUserId);
DECLARE @PatientId INT = (SELECT PatientId FROM Patients WHERE UserId=@PatientUserId);

-- Work schedule next 3 days, 2 slots/day
DECLARE @d0 DATE = CAST(GETDATE() AS DATE);
INSERT INTO DoctorSchedules(DoctorId, WorkDate, SlotStart, SlotEnd, MaxPatients)
VALUES
(@DoctorId, DATEADD(DAY, 0, @d0), '08:00', '10:00', 10),
(@DoctorId, DATEADD(DAY, 0, @d0), '13:00', '15:00', 10),
(@DoctorId, DATEADD(DAY, 1, @d0), '08:00', '10:00', 10),
(@DoctorId, DATEADD(DAY, 1, @d0), '13:00', '15:00', 10),
(@DoctorId, DATEADD(DAY, 2, @d0), '08:00', '10:00', 10),
(@DoctorId, DATEADD(DAY, 2, @d0), '13:00', '15:00', 10);

-- One demo appointment "approved" and record
DECLARE @ScheduleId INT = (SELECT TOP 1 ScheduleId FROM DoctorSchedules ORDER BY ScheduleId);
INSERT INTO Appointments(PatientId, DoctorId, ScheduleId, Reason, Status)
VALUES (@PatientId, @DoctorId, @ScheduleId, N'Khám tim mạch định kỳ', 'approved');

DECLARE @AppointmentId INT = SCOPE_IDENTITY();

INSERT INTO MedicalRecords(AppointmentId, DoctorId, Summary, Diagnosis, Note)
VALUES(@AppointmentId, @DoctorId, N'Hồi hộp, khó thở nhẹ', N'Tăng huyết áp độ 1', N'Theo dõi tại nhà');

DECLARE @RecordId INT = SCOPE_IDENTITY();

INSERT INTO Prescriptions(RecordId, DoctorId) VALUES(@RecordId, @DoctorId);
DECLARE @PrescriptionId INT = SCOPE_IDENTITY();

INSERT INTO PrescriptionItems(PrescriptionId, DrugName, Dosage, Frequency, Days, Note)
VALUES
(@PrescriptionId, N'Amlodipin 5mg', N'5mg', N'1 viên/ngày', 30, N'Uống sáng'),
(@PrescriptionId, N'Perindopril 4mg', N'4mg', N'1 viên/ngày', 30, N'Uống tối');

-- Thread và message demo
INSERT INTO MessageThreads(PatientId, DoctorId) VALUES(@PatientId, @DoctorId);
DECLARE @ThreadId INT = SCOPE_IDENTITY();

INSERT INTO Messages(ThreadId, FromUserId, ToUserId, Content)
VALUES(@ThreadId, @PatientUserId, @DoctorUserId, N'Chào bác sĩ, em hay chóng mặt buổi tối.');
